const array= [

    {id : 1,
    country : 'Espagne',
    city : 'Madrid',
    pic : 'https://www.okvoyage.com/wp-content/uploads/2019/10/visiter-Madrid.jpg',
    serie : 'Casa de Papel',
    affiche : 'https://static.posters.cz/image/750webp/101932.webp',
    airbnb : 'https://www.airbnb.fr/s/Madrid/homes' },
    
    {id : 2,
    country : 'Nouveau-Mexique',
    city : 'Albuquerque',
    pic : 'https://www.moi-voyageuse.com/IMG/jpg/albuquerque-old-town-10.jpg',
    serie : 'Breaking Bad',
    affiche : 'https://storage.googleapis.com/pod_public/1300/124250.jpg',
    airbnb : 'https://www.airbnb.fr/s/Albuquerque/homes' },
    
    {id : 3,
    country : 'Colombie',
    city : 'Medellin',
    pic : 'https://www.voyagecolombie.com/cdn/co-public/colombie_medellin_comuna13_c_goran_bogicevic_shutterstock-MAX-w1000h600.jpg',
    serie : 'Narcos',
    affiche : 'https://static.posters.cz/image/750webp/31851.webp',
    airbnb : 'https://www.airbnb.fr/s/Medellin/homes' },
    
    {id : 4,
    country : 'USA',
    city : 'Manhattan',
    pic : 'https://petitfute.twic.pics/medias/feg/05/96/059637.jpg?twic=v1/cover=780x439',
    serie : 'Suits',
    affiche : 'https://www.ecranlarge.com/uploads/image/001/028/suits-avocats-sur-mesure-photo-1028301.jpg',
    airbnb : 'https://www.airbnb.fr/s/Manhattan/homes' },
    
    {id : 5,
    country : 'Danemark',
    city : 'Copenhague',
    pic : 'https://media.routard.com/image/82/3/nyhavn-copenhague.1610823.jpg',
    serie : 'Vikings',
    affiche : 'https://m.media-amazon.com/images/I/61noa0sujTL._AC_SY679_.jpg',
    airbnb : 'https://www.airbnb.fr/s/Copenhague/homes' },
    
    {id : 6,
    country : 'Italie',
    city : 'Rome',
    pic : 'https://www.alibabuy.com/photos/library/1500/10763.jpg',
    serie : 'Rome',
    affiche : 'https://www.ecranlarge.com/uploads/image/001/149/1a1bwgwo3sw379vehr0vktue3xw-682.jpg',
    airbnb : 'https://www.airbnb.fr/s/Rome/homes' },
    
    {id : 7,
    country : 'France',
    city : 'Paris',
    pic : 'https://www.challenges.fr/assets/img/2018/08/02/cover-r4x3w1000-5c65492bc5e39-6110e936ab556bcf9c7e855130976eb6d6f430f7-jpg.jpg',
    serie : 'Lupin',
    affiche : 'https://fr.web.img6.acsta.net/pictures/20/12/02/16/24/1535547.jpg',
    airbnb : 'https://www.airbnb.fr/s/Paris/homes' },
    
    {id : 8,
    country : 'Angleterre',
    city : 'Birmingham',
    pic : 'https://a.cdn-hotels.com/gdcs/production85/d646/4a7f207a-74f4-495d-b452-ca16ac7f3140.jpg?impolicy=fcrop&w=800&h=533&q=medium',
    serie : 'Peaky Blinders',
    affiche : 'https://fr.web.img3.acsta.net/pictures/22/06/07/11/57/5231272.jpg',
    airbnb : 'https://www.airbnb.fr/s/Birmingham/homes' },
    
    {id : 9,
    country : 'USA',
    city : 'New-York',
    pic : 'https://www.alibabuy.com/photos/library/1500/10509.jpg',
    serie : 'YOU',
    affiche : 'https://fr.web.img6.acsta.net/pictures/18/10/22/11/41/0937031.jpg',
    airbnb : 'https://www.airbnb.fr/s/New-York/homes' },
    
    {id : 10,
    country : 'USA',
    city : 'Washington',
    pic : 'https://javitour.com/wp-content/uploads/2016/03/lugares-tur%C3%ADsticos-de-Washington-8_opt-1200x900.jpg',
    serie : 'House of Cards',
    affiche : 'https://fr.web.img4.acsta.net/pictures/19/07/18/10/08/0353053.jpg',
    airbnb : 'https://www.airbnb.fr/s/Washington/homes' },
    
    {id : 11,
    country : 'USA',
    city : 'Milwaukee',
    pic : 'https://assets.visitmilwaukee.org/visitmke/media/global/General%20Images/Gallery%20Size/VM-Milwaukee-Skyline-Drone-Discoveryworld.jpg?ext=.jpg&mode=crop&width=1200&height=600&scale=both&quality=80',
    serie : 'Dahmer',
    affiche : 'https://fr.web.img4.acsta.net/pictures/22/09/17/18/16/3249476.jpg',
    airbnb : 'https://www.airbnb.fr/s/Milwaukee/homes' },
    
    {id : 12,
    country : 'USA',
    city : 'Scranton',
    pic : 'http://res.cloudinary.com/simpleview/image/upload/v1554761055/clients/lackawannapa-redesign/Scranton_AfterDark_0155AccessAerial_44c662f6-1074-4d66-b293-7380de34fd29.jpg',
    serie : 'The Office',
    affiche : 'https://fr.web.img5.acsta.net/r_1280_720/pictures/14/02/04/13/20/128334.jpg',
    airbnb : 'https://www.airbnb.fr/s/Scranton/homes' },
    
    {id : 13,
    country : 'USA',
    city : 'San Jose',
    pic : 'https://www.arawak-experience.com/wp-content/uploads/2019/04/teatro_nacional_san_jose_costa_rica.jpg',
    serie : 'Good Doctor',
    affiche : 'https://www.ecranlarge.com/uploads/image/001/408/53wqewbwqq3wso6cowkznbym43-176.jpg',
    airbnb : 'https://www.airbnb.fr/s/San-Jose/homes' },
    
    {id : 14,
    country : 'USA',
    city : 'Los Angeles',
    pic : 'https://www.laquotidienne.fr/wp-content/uploads/2016/06/los-angeles-xl-airways.jpg',
    serie : 'Le Prince de Bel-Air',
    affiche : 'https://www.dhresource.com/0x0/f2/albu/g9/M00/47/6F/rBVaVVv1F9SAJp9gAAbXLVRQ-WI339.jpg',
    airbnb : 'https://www.airbnb.fr/s/Los-Angeles/homes' },
    
    {id : 15,
    country : 'Canada',
    city : 'Toronto',
    pic : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/10/2f/e4/toronto.jpg?w=700&h=500&s=1',
    serie : 'The Handmaids tale',
    affiche : 'https://www.ecranlarge.com/media/cache/1600x1200/uploads/image/001/026/the-handmaid-s-tale-saison-2-affiche-1026318.jpg',
    airbnb : 'https://www.airbnb.fr/s/Toronto/homes' },
    
    {id : 16,
    country : 'USA',
    city : 'Pasadena',
    pic : 'https://www.visittheusa.fr/sites/default/files/styles/16_9_1280x720/public/images/hero_media_image/2019-03/fb0f0042f11d88faabfb426de8c10739.jpeg?h=415b5158&itok=1mHpbL0j',
    serie : 'The Big Bang Theory',
    affiche : 'https://static.posters.cz/image/1300/art-photo/the-big-bang-theory-equipe-i106240.jpg',
    airbnb : 'https://www.airbnb.fr/s/Pasadena/homes' },
    
    {id : 17,
    country : 'USA',
    city : 'Baltimore',
    pic : 'https://www.visitmaryland.org/sites/default/files/styles/editorial_hero/public/2020-08/Inner-Harbor-%40jarasaurus-Instagram-1190x793.jpg?h=b6db544b&itok=7R8KTin-',
    serie : 'The Wire',
    affiche : 'https://fr.web.img4.acsta.net/pictures/21/02/11/13/49/0944070.jpg',
    airbnb : 'https://www.airbnb.fr/s/Baltimore/homes' },
    
    {id : 18,
    country : 'USA',
    city : 'Honolulu',
    pic : 'https://www.busytourist.com/wp-content/uploads/2019/08/things-to-do-in-Honolulu.jpg',
    serie : 'Lost',
    affiche : 'https://m.media-amazon.com/images/I/317I44JE+JL._AC_.jpg',
    airbnb : 'https://www.airbnb.fr/s/Honolulu/homes' },
    
    {id : 19,
    country : 'Croatie',
    city : 'Dubrovnik',
    pic : 'https://www.explorizy.com/uploads/media/default/0001/01/thumb_163_default_col_lg_8.jpeg',
    serie : 'Game of Thrones',
    affiche : 'https://m.media-amazon.com/images/I/61+5mMtkPbL._AC_SL1024_.jpg',
    airbnb : 'https://www.airbnb.fr/s/Dubrovnik/homes', },
    
    {id : 20,
    country : 'Japon',
    city : 'Tokyo',
    pic : 'https://beborghi.com/wp-content/uploads/2019/12/beborghi__Giappone_Tokyo-Asakusa.jpg',
    serie : 'Alice in Borderland',
    affiche : 'https://fr.web.img6.acsta.net/pictures/20/11/06/12/24/4584296.jpg',
    airbnb : 'https://www.airbnb.fr/s/Tokyo/homes' },
    
    {id : 21,
    country : 'Ukraine',
    city : 'Tchernobyl',
    pic : 'https://4.bp.blogspot.com/-P16TVrxbfIQ/UBVuXOvQSZI/AAAAAAAAGe4/WW59njZtAo0/s1600/PRIPYAT+Russie+-+05.jpg',
    serie : 'Chernobyl',
    affiche : 'https://fr.web.img6.acsta.net/r_1920_1080/pictures/21/02/11/14/15/4218723.jpg',
    airbnb : 'https://www.airbnb.fr/s/Chernobyl/homes' },
    
    {id : 22,
    country : 'Angleterre',
    city : 'Londres',
    pic : 'https://img-4.linternaute.com/XpIsCRiVK7U1-WLObg9ol0UyFUc=/1500x/smart/ba429abadd8a4731be516a2465ca749f/ccmcms-linternaute/10993851.jpg',
    serie : 'Sex Education',
    affiche : 'https://fr.web.img5.acsta.net/r_1280_720/pictures/19/01/03/10/55/2296345.jpg',
    airbnb : 'https://www.airbnb.fr/s/Londres/homes' },
    
    {id : 23,
    country : 'USA',
    city : 'Atlanta',
    pic : 'https://www.ou-et-quand.net/partir/images/illustration/atlanta-georgie_809.jpg',
    serie : 'Stranger Things',
    affiche : 'https://waasabi.com/medias/158646037680.jpg',
    airbnb : 'https://www.airbnb.fr/s/Atlanta/homes' },
    
    {id : 24,
    country : 'USA',
    city : 'Miami',
    pic : 'https://media.bizj.us/view/img/11064209/pmg-300bis-05-photomontage-02*750xx8000-4500-0-382.jpg',
    serie : 'Dexter',
    affiche : 'https://fr.web.img6.acsta.net/r_1280_720/pictures/210/489/21048948_20131011212508917.jpg',
    airbnb : 'https://www.airbnb.fr/s/Miami/homes' },
    
    {id : 25,
    country : 'USA',
    city : 'Brooklyn',
    pic : 'https://media.ceetiz.com/activity/IOTNYC005/visite-brooklyn-dumbo-ceetiz-2.jpg',
    serie : 'Brooklyn Nine-Nine',
    affiche : 'https://fr.web.img5.acsta.net/r_1280_720/pictures/20/01/10/10/23/0734068.jpg',
    airbnb : 'https://www.airbnb.fr/s/Brooklyn/homes' },
    
    {id : 26,
    country : 'Ecosse',
    city : 'Glasgow',
    pic : 'https://media.timeout.com/images/105400989/750/422/image.jpg',
    serie : 'Andor',
    affiche : 'https://fr.web.img6.acsta.net/pictures/22/09/12/09/51/0326456.jpg',
    airbnb : 'https://www.airbnb.fr/s/Glasgow/homes' }
    ]

    export default array